models/User.php
<?php

namespace app\models;

use Yii;
use yii\web\IdentityInterface;
use yii\web\Linkable;
use yii\db\ActiveRecord;
use yii\base\NotSupportedException;
use app\models\Level;
use app\models\Activity;

class User extends ActiveRecord implements IdentityInterface
{

    const ROLE_USER = 0;
    const ROLE_MODERATOR = 1;
    const ROLE_ADMIN = 2;
    const ROLE_SUPERADMIN = 3;
    
    public static function tableName()
    {
        return 'user';
    }
    public function rules()
    {
        return [
            [['name', 'email', 'password_hash'], 'required'],
            ['password_hash', 'match', 'pattern' => '/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(.{7,})$/', 'message' => \Yii::t('main', 'The password must be at least 7 characters long including uppercase and lowercase letters, digits')],
            ['name', 'string', 'max' => 32, 'tooLong' => \Yii::t('main', 'Name is too long (maximum is {max} characters)', array(32))],
            ['name', 'match', 'pattern' => '/^[\w\.\s\-\,]+$/u', 'message' => 'Only following characters are allowed in Name: "A-Z", "0-9", "_", ".", "-", ","'],
            ['email', 'email'],
        ];
    }
    
    public function getLevels()
    {
        return $this->hasOne(Level::className(), ['id' => 'level']);
    }
    
    public function getActivities()
    {
        return $this->hasMany(Activity::className(), ['user_id' => 'id']);
    }
    
    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['auth_key' => $token]);
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['email' => $username]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }
    
    public function getUser()
    {
        return User::findIdentity(Yii::$app->user->identity->id);
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }
}

controllers/DictionaryController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Category;
use app\models\RuItLanguages;
use app\models\RuLanguage;
use app\models\ItLanguage;
use app\models\User;
use yii\db\Query;
use yii\web\Controller;

class DictionaryController extends Controller
{
    public function actionIndex() {
        $modelCategory = Category::find()->where(['user_id' => [Category::DEFAULT_CATEGORY, Yii::$app->user->identity->id]])->all();
        $query = new Query;
        $countWords = $query->from('ru_it_languages as r')
                ->innerJoin('category as c', 'r.id_category = c.id')
                ->where(['c.user_id' => [Category::DEFAULT_CATEGORY, Yii::$app->user->identity->id]])->count();
        return $this->render('index', array('modelCategory' => $modelCategory, 'countWords' => $countWords, 'isAllUsers' => true));
    }
    
    public function actionGenerateWords() {
        $categoryId = Yii::$app->request->post('categoryId', false);
        if(!$categoryId) {
            $modelCategory = Category::find()->where(['user_id' => [Category::DEFAULT_CATEGORY, Yii::$app->user->identity->id]])->all();
            $isAllUsers = true;
        } else {
            $modelCategory = Category::find()->where(['id' => $categoryId])->all();
            $isAllUsers = false;
        }
        
        $isCustom = Yii::$app->user->identity->id == $modelCategory[0]->user_id ? true : false;
        $data = $this->renderPartial('block/words', [
            'modelCategory' => $modelCategory,
            'isAllUsers' => $isAllUsers
                ]);
        
        echo json_encode(['data' => $data, 'isCustom' => $isCustom]);
    }
    
    public function actionGetCategories() {
        $modelCategory = Category::find()->all();
        $categories = [];
        $i = 0;
        foreach($modelCategory as $category) {
            $categories[$i]['id'] = $category->id;
            $categories[$i]['category'] = $category->category;
            $i++;
        }
        echo json_encode(['categories' => $categories]);
    }
    
    public function actionSetCategory() {
        if(Yii::$app->user->identity->role != User::ROLE_SUPERADMIN)
            return;
        $categoryId = (int) Yii::$app->request->post('categoryId', 0);
        $idWordId = Yii::$app->request->post('itWordId', 0);
        $languages = RuItLanguages::model()->updateAll(array('id_category' => $categoryId), 'id_it = :id', array(':id' => $idWordId));
        RuItLanguages::updateAll(['id_category' => $categoryId], ['id_it' => $idWordId]);
        $modelCategory = Category::find()->all();
        $isAllUsers = true;
        
        $data = $this->renderPartial('block/words', [
            'modelCategory' => $modelCategory,
            'isAllUsers' => $isAllUsers
                ]);
        echo json_encode(['status' => 'success', 'html' => $data]);
    }
    
    public function actionSetCustomCategory() {
        $itWords = Yii::$app->request->post('itWords', 0);
        $ruWords = Yii::$app->request->post('ruWords', 0);
        
        $modelUser = User::findIdentity(Yii::$app->user->identity->id);
        $name = $modelUser->name;
        $customCategory = Category::find()->where(['user_id' => Yii::$app->user->identity->id])->one();
        if(empty($customCategory)) {
            $customCategory = new Category();
            $customCategory->user_id = $modelUser->id;
            $customCategory->category = 'C' . $modelUser->name;
            $customCategory->save();
        }
        
        $cId = $customCategory->id;
        $countWords = count($itWords);
        for($i = 0; $i < $countWords; $i++) {
            $RuIt = RuItLanguages::find()->where(['id_ru' => $ruWords[$i], 'id_it' => $itWords[$i], 'id_category' => $cId])->one();
            if(!empty($RuIt))
                continue;
            $RuIt = new RuItLanguages();
            $RuIt->id_ru = $ruWords[$i];
            $RuIt->id_it = $itWords[$i];
            $RuIt->id_category = $cId;
            $RuIt->save();
        }
    }
    
    public function actionCleanCustomCategory() {
        $categoryId = Category::find()->where(['user_id' => Yii::$app->user->identity->id])->one()->id;
        RuItLanguages::deleteAll(['id_category' => $categoryId]);
    }
    
    
    public function actionUpdateRuWord() {
        if(Yii::$app->user->identity->role != User::ROLE_SUPERADMIN)
            return;
        $ruWordId = Yii::$app->request->post('ruWordId', 0);
        $ruWord = Yii::$app->request->post('ruWord', 0);
        $modelRu = RuLanguage::find(['id' => $ruWordId]);
        $modelRu->word = $ruWord;
        $modelRu->save();
        //$data = $this->renderPartial('block/words', array('modelCategory' => $modelCategory, 'isAllUsers' => $isAllUsers), true);
        //echo json_encode(array('status' => 'success', 'html' => $data));
    }
    
    public function actionUpdateItWord() {
        if(Yii::app()->user->getUser()->role != User::ROLE_SUPERADMIN)
            return;
        $itWordId = Yii::$app->request->post('itWordId', 0);
        $itWord = Yii::$app->request->post('itWord', 0);
        $modelIt = ItLanguage::find(['id' => $itWordId]);
        $modelIt->word = $itWord;
        $modelIt->save();
        //$data = $this->renderPartial('block/words', array('modelCategory' => $modelCategory, 'isAllUsers' => $isAllUsers), true);
        //echo json_encode(array('status' => 'success', 'html' => $data));
    }
}

controllers/RuleController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\User;
use app\models\Activity;

class RuleController extends Controller
{
    const NOUNS_TESTS = 1;
    
    public function actionIndex() {
        $data = $this->renderPartial('menu');
        return $this->render('index', ['data' => $data]);
    }
    
    public function actionAlphabet() {
        $data = $this->renderPartial('menu');
        return $this->render('alphabet', ['data' => $data]);
    }
    
    public function actionGrammar() {
        $data = $this->renderPartial('menu');
        return $this->render('grammar', ['data' => $data]);
    }
    
    public function actionNouns() {
        $data = $this->renderPartial('menu');
        return $this->render('nouns', ['data' => $data]);
    }
    
    public function actionNounstest() {
        return $this->render('tests/nounstest');
    }
    
    public function actionNounsGenerate() {
        $test = Yii::$app->request->post('test', -1);
        $testNum = Yii::$app->request->post('testNum', -1);
        if($test == -1 || $testNum == -1)
            die();
        
        if($test >= self::NOUNS_TESTS) {
            echo json_encode(['end' => true]);
            die();
        }
        
        //if(!$this->getViewFile('tests\\nouns\\test1' . $test)) { for local server
        if(!file_exists($this->getViewPath() . '/tests/nouns/test' . $testNum . $test .'.php')) {
            echo json_encode(['status' => false, 'end' => false]);
            die();
        }
        
        $dataTest = 'tests/nouns/test' . $testNum . $test;
        $data = $this->renderPartial($dataTest);
        echo json_encode(['status' => true, 'end' => false, 'data' => $data]);
    }
    
    public function actionAfterTest() {
        $experience = (int) Yii::$app->request->post('experience');
        
        $modelUser = User::findIdentity(Yii::$app->user->identity->id);
        
        $modelUser->experience += $experience;
        $modelUser->total_experience += $experience;

        $modelActivity = Activity::find()->where(['date' => date('Y-m-d'), 'user_id' => Yii::$app->user->identity->id])->one();
        if(empty($modelActivity)) {
            $modelActivity = new Activity;
            $modelActivity->date = date('Y-m-d');
            $modelActivity->user_id = Yii::$app->user->identity->id;
        }
        $modelActivity->gain_experience = $experience;

        $points = substr($experience, strlen($experience)-1);
        if($points == 0) {
            $pointsText = \Yii::t('main', 'очков');
        } elseif($points == 1) {
            $pointsText = \Yii::t('main', 'очко');
        } elseif($points >= 2 && $points <= 4) {
            $pointsText = \Yii::t('main', 'очкa');
        } elseif($points >= 5 && $points <= 9) {
            $pointsText = \Yii::t('main', 'очков');
        }
        $gainedExperienceText = '+' . $experience . ' ' . $pointsText;
        $gainedLevel = false;
        $gainedLevelText = '';
        if($modelUser->experience >= $modelUser->levels->experience) {
            $gainedLevel = true;
            $diffExperience = $modelUser->experience - $modelUser->levels->experience;
            $modelUser->experience = $diffExperience;
            $modelUser->level += 1;
            if(empty(json_decode($modelActivity->gain_achievements)->{"level"})) {
                $modelActivity->gain_achievements = json_encode(['level' => [['Reached level ', $modelUser->level]]]);
            } else {
                $levelAchieves = json_decode($modelActivity->gain_achievements);
                $levelAchieves->{"level"}[] = ['Reached level ', $modelUser->level];
                $modelActivity->gain_achievements = json_encode($levelAchieves);
            }
            $gainedLevelText = \Yii::t('main', 'Level up!');
        }
        $modelUser->save(false);
        $modelActivity->save(false);
        $headerProgress = $this->renderPartial('block/header_progress', [
            'userModel' => $modelUser
            ]);
        
        echo json_encode(['status' => true, 'end' => true, 'headerProgress' => $headerProgress]);
    }
}

views/layouts/landing.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use app\assets\LandingAsset;

LandingAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <!-- blueprint CSS framework -->
        <link href="<?= Yii::$app->request->baseUrl; ?>/images/favicon-flag_italy.png" rel="icon" type="image/x-icon" />

        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
        <?php $this->beginBody() ?>
        <div class="page-screen">
            <img src="<?= Yii::$app->request->baseUrl ?>/images/page_loader.gif" />
        </div>
        <div class="home">
            <a href="<?= Url::to('site/home') ?>">Главная</a>
        </div>
        
        <div class="signin">
            <a href="<?= Url::to('authorization') ?>">Войти</a>
        </div>
        <?= $content ?>
        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<!DOCTYPE html>
<?php
use yii\widgets\ActiveForm;
use app\models\LoginForm;
use app\models\User;
use yii\helpers\Html;
use yii\helpers\Url;
use app\assets\AppAsset;

$model = new LoginForm;
$id = !empty(Yii::$app->user->identity) ? Yii::$app->user->identity->id : false;
$userModel = User::findIdentity($id);

AppAsset::register($this);

?>
<?php $this->beginPage() ?>
<html lang="en">
    <head>

        <!-- blueprint CSS framework -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
        <?= Html::csrfMetaTags() ?>
        <link href="<?php echo Yii::$app->request->baseUrl; ?>/images/favicon-flag_italy.png" rel="icon" type="image/x-icon" />

    </head>
    <body>
         <?php $this->beginBody() ?>
        <div class="wrap">
            <div class="content">
                <div class="header">
                    <div class="header-brand">
                        <div class="brand">
                            <i class="icon icon-brand"></i><div class="header-brand-text">Italian 100%</div>
                        </div>
                    </div>
                    <ul>
                        <?php if(Yii::$app->user->isGuest): ?>
                        <li><a href="<?= Url::toRoute('authorization') ?>"><?= 'Войти'; ?></a></li>
                        <li><a href="#"><?= 'Зарегистрироваться'; ?></a></li>
                        <?php else: ?>
                        <li><a href="<?= Url::toRoute('/site/logout') ?>"><?= 'Выйти'; ?></a></li>
                        <li><a href="<?= Url::toRoute('/site/home') ?>"><?= 'Главная'; ?></a></li>
                        <li><a href="<?= Url::toRoute('/dictionary/index') ?>"><?= 'Словарь'; ?></a></li>
                        <li><a href="<?= Url::toRoute('/site/tasks') ?>"><?= 'Тренировка'; ?></a></li>
                        <li><a href="<?= Url::toRoute('/rule/index') ?>"><?= 'Правила'; ?></a></li>
                            <?php if(Yii::$app->user->identity->role == User::ROLE_SUPERADMIN): ?>
                            <li><a href="<?= Url::toRoute('/superadmin/index') ?>"><?= 'Суперадмин'; ?></a></li>
                            <?php endif; ?>
                        <?php endif; ?>
                    </ul>
                    <div class="header-profile">
                        <div class="header-progress">
                            <div class="profile-level">
                                <?= \Yii::t('main', 'Level'); ?> <?= !empty($userModel) ? $userModel->level : '0'?>
                            </div>
                            <div class="profile-experience">
                                <div class="profile-experience-progress" 
                                     data-experience-progress="<?= !empty($userModel) ? $userModel->experience : 0; ?>" 
                                     data-experience-total="<?= !empty($userModel) ? $userModel->levels->experience : 0; ?>">
                                </div>
                                <div class="profile-experience-show">
                                    <?php
                                    $pointsText = 'очков';
                                    if(!empty($userModel)) {
                                        $points = substr($userModel->experience, strlen($userModel->experience)-1);
                                        if($points == 0) {
                                            $pointsText = 'очков';
                                        } elseif($points == 1) {
                                            $pointsText = 'очко';
                                        } elseif($points == 2 || $points == 3 || $points == 4) {
                                            $pointsText = 'очка';
                                        } elseif($points == 5 || $points == 6 || $points == 7 || $points == 8 || $points == 9) {
                                            $pointsText = 'очков';
                                        }
                                    }
                                    ?>
                                    <?= !empty($userModel) ? $userModel->experience : '0'?> <?= $pointsText; ?>
                                </div>
                            </div>
                        </div>
                        <div class="header-avatar">
                            <div class="div-avatar">
                                <a href="<?= Url::toRoute('/site/profile') ?>" class="avatar" style="background-image: url('<?= (!empty($userModel) && !empty($userModel->file_avatar)) ? "/uploads/{$userModel->file_avatar}" : '/images/default-avatar.png';?>')"></a>
                            </div>
                            <div class="profile-popup">
                                <div class="profile-popup-user_info">
                                    <div class="div-profile-popup-user-avatar">
                                        <a href="<?= Url::toRoute('/site/profile') ?>" class="profile-popup-user-avatar" style="background-image: url('<?= (!empty($userModel) && !empty($userModel->file_avatar)) ? "/uploads/{$userModel->file_avatar}" : '/images/default-avatar.png';?>')"></a>
                                    </div>
                                    <div class="profile-popup-user-content">
                                        <a href="<?= Url::toRoute('/site/profile') ?>" class="user-content-name">
                                            <?= empty(Yii::$app->user->identity) ? 'Guest' : Yii::$app->user->identity->name; ?>
                                        </a>
                                        <div class="user-content-email">
                                            <?= !empty($userModel) ? $userModel->email : '';?>
                                        </div>
                                    </div>
                                </div>
                                <div class="profile-popup-menu_info">
                                    
                                </div>
                            </div>
                        </div>
                        <div class="header-name">
                            <div class="username">
                                <?= empty(Yii::$app->user->identity) ? 'Guest' : Yii::$app->user->identity->name; ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="mobile">
                    <div class="header-mobile menu">
                        <div class="header-profile">
                            <div class="header-progress">
                                <div class="profile-level">
                                    <?= !empty($userModel) ? $userModel->level : '0'?>
                                </div>
                                <div class="profile-experience">
                                    <div class="profile-experience-progress" 
                                         data-experience-progress="<?= !empty($userModel) ? $userModel->experience : 0; ?>" 
                                         data-experience-total="<?= !empty($userModel) ? $userModel->levels->experience : 0; ?>">
                                    </div>
                                    <div class="profile-experience-show">
                                        <?php
                                        $pointsText = 'очков';
                                        if(!empty($userModel)) {
                                            $points = substr($userModel->experience, strlen($userModel->experience)-1);
                                            if($points == 0) {
                                                $pointsText = 'очков';
                                            } elseif($points == 1) {
                                                $pointsText = 'очко';
                                            } elseif($points == 2 || $points == 3 || $points == 4) {
                                                $pointsText = 'очка';
                                            } elseif($points == 5 || $points == 6 || $points == 7 || $points == 8 || $points == 9) {
                                                $pointsText = 'очков';
                                            }
                                        }
                                        ?>
                                        <?= !empty($userModel) ? $userModel->experience : '0'?> <?= $pointsText; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="header-avatar">
                                <div class="div-avatar">
                                    <a href="<?= Url::toRoute('/site/profile') ?>" class="avatar" style="background-image: url('<?php echo (!empty($userModel) && !empty($userModel->file_avatar)) ? "/uploads/{$userModel->file_avatar}" : '/images/default-avatar.png';?>')"></a>
                                </div>
                            </div>
                            <div class="header-name">
                                <div class="username">
                                    <?= empty(Yii::$app->user->identity) ? 'Guest' : Yii::$app->user->identity->name; ?>
                                </div>
                            </div>
                        </div>
                        <button class="hamburger">&#9776;</button>
                        <button class="cross">&#10006;</button>
                    </div>
                    <div class="menu-mobile">
                        <ul>
                            <?php if(Yii::$app->user->isGuest): ?>
                            <li><a href="<?= Url::toRoute('authorization') ?>"><?= 'Войти'; ?></a></li>
                            <li><a href="#"><?= 'Зарегистрироваться'; ?></a></li>
                            <?php else: ?>
                            <li><a href="<?= Url::toRoute('/site/logout') ?>"><?= 'Выйти'; ?></a></li>
                            <li><a href="<?= Url::toRoute('/site/home') ?>"><?= 'Главная'; ?></a></li>
                            <li><a href="<?= Url::toRoute('/dictionary/index') ?>"><?= 'Словарь'; ?></a></li>
                            <li><a href="<?= Url::toRoute('/site/tasks') ?>"><?= 'Тренировка'; ?></a></li>
                            <li><a href="<?= Url::toRoute('/rule/index') ?>"><?= 'Правила'; ?></a></li>
                                <?php if(Yii::$app->user->identity->role == User::ROLE_SUPERADMIN): ?>
                                <li><a href="<?= Url::toRoute('/superadmin/index') ?>"><?= 'Суперадмин'; ?></a></li>
                                <?php endif; ?>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
                <div class="main">
                    <?= $content ?>
                </div>
            </div>
        </div>
        <?php $this->endBody() ?>
    </body>
<div id="cursorTooltip" class="cursorTooltip" style="visibility: hidden; position: absolute; top: 0; left: 0;">
    С такими успехами следующий уровень получишь через <strong>5</strong> дней
</div>
</html>
<?php $this->endPage() ?>

views/layouts/main1.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'navbar-form'])
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->name . ')',
                    ['class' => 'btn btn-link']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>