models/ItLanguage.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use app\models\RuLanguage;
use app\models\RuItLanguages;
use app\models\Category;

class ItLanguage extends ActiveRecord
{
    public static function tableName()
    {
        return 'it_language';
    }
    
    public function rules()
    {
        return [
            ['word', 'required'],
            ['word', 'unique']
        ];
    }
    
    /*public function relations()
    {
        return array(
            //'RuLanguages' => array(self::MANY_MANY, 'RuLanguage', 'ru_it_languages(id_it, id_ru)'),
            'Translate' => array(self::MANY_MANY, 'RuLanguage', 'ru_it_languages(id_it, id_ru)'),
            //'RuItLanguages' => array(self::BELONGS_TO, 'RuItLanguages', 'id'),
            'Categories' => array(self::MANY_MANY, 'Category', 'ru_it_languages(id_it, id_category)'),
        );
    }*/
    
    public function getTranslates()
    {
        return $this->hasMany(RuLanguage::className(), ['id' => 'id_ru'])
                ->viaTable('ru_it_languages', ['id_it' => 'id']);
    }
}

models/User.php
<?php

namespace app\models;

use Yii;
use yii\web\IdentityInterface;
use yii\web\Linkable;
use yii\db\ActiveRecord;
use yii\base\NotSupportedException;
use app\models\Level;
use app\models\Activity;

class User extends ActiveRecord implements IdentityInterface
{

    const ROLE_USER = 0;
    const ROLE_MODERATOR = 1;
    const ROLE_ADMIN = 2;
    const ROLE_SUPERADMIN = 3;
    
    public static function tableName()
    {
        return 'user';
    }
    public function rules()
    {
        return [
            [['name', 'email', 'password_hash'], 'required'],
            ['password_hash', 'match', 'pattern' => '/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(.{7,})$/', 'message' => \Yii::t('main', 'The password must be at least 7 characters long including uppercase and lowercase letters, digits')],
            ['name', 'string', 'max' => 32, 'tooLong' => \Yii::t('main', 'Name is too long (maximum is {max} characters)', array(32))],
            ['name', 'match', 'pattern' => '/^[\w\.\s\-\,]+$/u', 'message' => 'Only following characters are allowed in Name: "A-Z", "0-9", "_", ".", "-", ","'],
            ['email', 'email'],
        ];
    }
    
    public function getLevels()
    {
        return $this->hasOne(Level::className(), ['id' => 'level']);
    }
    
    public function getActivities()
    {
        return $this->hasMany(Activity::className(), ['user_id' => 'id']);
    }
    
    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['auth_key' => $token]);
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['email' => $username]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }
    
    public function getUser()
    {
        return User::findIdentity(Yii::$app->user->identity->id);
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\RegistrationForm;
use app\models\Category;
use app\models\User;
use app\models\ItLanguage;
use app\models\RuItLanguages;
use app\models\RuLanguage;
use app\models\Activity;
use yii\helpers\Url;
use yii\web\HttpException;
use yii\web\Controller;
use yii\db\Query;

class SiteController extends Controller
{
    
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actions() {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
    
    public function beforeAction($action) {
        
        //actionRepeat, actionConstructor
        if(in_array("{$action->id}", ['repeat', 'constructor'])) {
            Yii::$app->session->set('temp', [
                'temp_correct_answers' => 0,
                'temp_correct_answer_id' => [],
                'temp_current_words' => [],
                ]);
            
            $cache = Yii::$app->cache;
            $data = $cache->get('translateModel');
            if($data)
                $cache->delete('translateModel');
            
            $data = $cache->get('mainModel');
            if($data)
                $cache->delete('mainModel');
        }
        
        return parent::beforeAction($action);
    }
    
    public function actionIndex() {
        $this->layout = 'landing';
        return $this->render('index');
    }
    
    public function actionAuthorization() {
        $form = Yii::$app->request->post('ajax', false);
        if($form) {
            if($form == 'login-form') {
                $model = new LoginForm();
                $model->email = Yii::$app->request->post('LoginForm')['email'];
                $model->password = Yii::$app->request->post('LoginForm')['password'];
                if ($model->login()) {
                    return $this->redirect(Url::to('site/home'));
                }
            } elseif($form == 'registration-form') {
                $model = new RegistrationForm();
                $model->firstname = Yii::$app->request->post('RegistrationForm')['firstname'];
                $model->sex = Yii::$app->request->post('RegistrationForm')['sex'];
                $model->email = Yii::$app->request->post('RegistrationForm')['email'];
                $model->password = Yii::$app->request->post('RegistrationForm')['password'];
                if($model->registrate()) {
                    $login = new LoginForm(['email' => $model->email, 'password' => $model->password]);
                    if($login->login())
                        return $this->redirect(Url::to('site/home'));
                }
            }
        }
        $this->layout = 'landing';
        return $this->render('authorization');
    }
    
    public function actionHome() {
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(Yii::$app->request->referrer);
        }
        return $this->render('home');
    }
    
    public function actionRepeat($language) {
        $language = Yii::$app->request->get('language', false);
        $category = Yii::$app->request->get('category', false);
        $cache = Yii::$app->cache;
        if(!$language)
            throw new HttpException(500,Yii::t('yii','Language is not selected.'));
        
        $query = new Query();
        $query2 = new Query();
        $queryIds = new Query();
        
        $trainingLimit = Yii::$app->session->get('user.trainingLimit');
        
        $queryIds->from('ru_it_languages as main');
        if($language == 'ru') {
            $queryIds->select('main.id_ru as id');
        } elseif($language == 'it') {
            $queryIds->select('main.id_it as id');
        }
        if($category) {
            $queryIds->andWhere(['main.id_category' => $category]);
        }
        $ids = $queryIds->orderBy('RAND()')->limit($trainingLimit)->all();
        if(count($ids) < $trainingLimit) {
            $trainingLimit = count($ids);
        }
        
        if($language == 'ru') {
            $query->from('ru_language as main')
                    ->innerJoin('ru_it_languages as ru_it', 'ru_it.id_ru = main.id')
                    ->innerJoin('it_language as translate', 'translate.id = ru_it.id_it');
            
            $query2->from('ru_language as main')
                    ->innerJoin('ru_it_languages as ru_it', 'ru_it.id_ru = main.id')
                    ->innerJoin('it_language as translate', 'translate.id = ru_it.id_it');
        } elseif($language == 'it') {
            $query->from('it_language as main')
                    ->innerJoin('ru_it_languages as ru_it', 'ru_it.id_it = main.id')
                    ->innerJoin('ru_language as translate', 'translate.id = ru_it.id_ru');
            
            $query2->from('it_language as main')
                    ->innerJoin('ru_it_languages as ru_it', 'ru_it.id_it = main.id')
                    ->innerJoin('ru_language as translate', 'translate.id = ru_it.id_ru');
            
        }
        if($category) {
            $query->andWhere(['ru_it.id_category' => $category]);
        }
        
        //SELECT CONCAT(UPPER(LEFT(main.word,1)), LOWER(SUBSTRING(main.word,2,LENGTH(main.word))));
        //UPDATE it_language SET word = CONCAT(UPPER(LEFT(word,1)), LOWER(SUBSTRING(word,2,LENGTH(word))))
        $query2->select('main.id as main_id, main.word as main_word, translate.id as translate_id, translate.word as translate_word')
                    ->orderBy('RAND()')
                    ->limit(4);
        $query->select('main.id as main_id, main.word as main_word, translate.id as translate_id, translate.word as translate_word')
                ->union($query2);
        $words = [];
        
        foreach($ids as $id) {
            $query2->where(['!=', 'main.id', $id['id']]);
            $query->where(['main.id' => $id['id']]);
            $temp = $query->all();
            $words = array_merge($words, $temp);
        }
        
        return $this->render('repeat', ['words' => $words, 'trainingLimit' => $trainingLimit]);
    }
    
    public function actionSetPoints() {
        $startTime = microtime(1);
        $answerId = Yii::$app->request->post('answerId', 0);
        $isFinish = Yii::$app->request->post('finish', false);
        $correctAnswer = Yii::$app->request->post('rightAnswer', false);
        $correctAnswer = $correctAnswer == "true" ? true : false;

        $temp = Yii::$app->session->get('temp');
        array_push($temp['temp_current_words'], $answerId);
        if($correctAnswer) {
            array_push($temp['temp_correct_answer_id'], $answerId);
            $temp['temp_correct_answers'] = $temp['temp_correct_answers'] + 1;
        }
        Yii::$app->session->set('temp', $temp);
        
        if($isFinish) {
            $modelActivity = Activity::find()
                    ->where(['date' => date('Y-m-d'), 'user_id' => Yii::$app->user->identity->id])
                    ->one();
            $modelUser = User::findIdentity(Yii::$app->user->identity->id);
            $modelUser->experience += $temp['temp_correct_answers'];
            $modelUser->total_experience += $temp['temp_correct_answers'];
            
            $pointsText = RuLanguage::setPointsWord($temp['temp_correct_answers']);
            $gainedExperienceText = '+' . $temp['temp_correct_answers'] . ' ' . $pointsText;
            $gainedLevel = false;
            $gainedLevelText = '';
            if($modelUser->experience >= $modelUser->levels->experience) {
                $gainedLevel = true;
                $diffExperience = $modelUser->experience - $modelUser->levels->experience;
                $modelUser->experience = $diffExperience;
                $modelUser->level += 1;
                if(empty(json_decode($modelActivity->gain_achievements)->{"level"})) {
                    $modelActivity->gain_achievements = json_encode(['level' => [['Reached level ', $modelUser->level]]]);
                } else {
                    $levelAchieves = json_decode($modelActivity->gain_achievements);
                    $levelAchieves->{"level"}[] = ['Reached level ', $modelUser->level];
                    $modelActivity->gain_achievements = json_encode($levelAchieves);
                }
                $gainedLevelText = \Yii::t('main', 'Level up!');
            }
            if(empty($modelActivity)) {
                $modelActivity = new Activity;
                $modelActivity->date = date('Y-m-d');
                $modelActivity->user_id = Yii::$app->user->identity->id;
                $modelActivity->gain_experience = $temp['temp_correct_answers'];
            } else {
                $modelActivity->gain_experience += $temp['temp_correct_answers'];
            }
            $modelUser->save(false);
            $modelActivity->save(false);
            $headerProgress = $this->renderPartial('block/header_progress', [
                'userModel' => $modelUser
                ]);
            $result = $this->renderPartial('block/result', [
                'words' => $temp['temp_current_words'], 
                'rightAnswers' => $temp['temp_correct_answer_id'], 
                'gainedExperienceText' => $gainedExperienceText,
                'gainedLevel' => $gainedLevel,
                'gainedLevelText' => $gainedLevelText,
                    ]);

views/site/block/add_new_word.php
<?php
$totalWords = 0;
?>
<form class="form-style-4" action="/site/create" method="post">
    <div class="index-item-add-word">
        <div class="row">
            <div class="col-lg-9 col-xs-9">
                <div class="ml30">
                    <div class="index-item-category mb50 mt15">
                            <select class="cs-select cs-skin-overlay" name="Category">
                                <option value="" disabled <?php empty($selectedCategory) ? 'selected' : '' ?>><?php echo Yii::t('main', 'Select a category'); ?></option>
                                <optgroup label="<?php echo Yii::t('main', 'Category'); ?>">
                                <?php foreach($modelCategory as $key => $category): ?>
                                    <option value="<?php echo $category->id ?>" <?php echo !empty($selectedCategory) && $selectedCategory == $category->id ? 'selected' : '' ?>><?php echo Yii::t('main', $category->category); ?></option>
                                <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="<?php echo Yii::t('main', 'Words'); ?>">
                                    <?php foreach($modelCategory as $key => $category): ?>
                                    <?php $totalWords += count($category->RuLanguages); ?>
                                    <option data-no-select><?php echo count($category->RuLanguages) . ' ' . Yii::t('main', 'words');?></option>
                                <?php endforeach; ?>
                                </optgroup>
                                    <option data-no-select><?php echo $totalWords . ' ' . Yii::t('main', 'words');?></option>
                            </select>
                    </div>
                    <div class="index-item-translate">
                        <div class="index-item-translate-it mb45">
                            <label>
                                Versione italiana
                            </label>
                            <input type="text" name="ItInput" autocomplete="off">
                        </div>
                        <div class="index-item-translate-ru">
                            <label>
                                Русский вариант
                            </label>
                            <input type="text" name="RuInput" autocomplete="off">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-xs-3">
                <div class="icon-new-word-div">
                    <i class="icons icon-new-word"></i>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-xs-12">
                <div class="mt40" style="text-align: center;">
                    <button type="submit" class="button31"></button>
                </div>
            </div>
        </div>
    </div>
</form>

views/site/block/constructor_word.php
<?php
$letters = str_split($word->word);
$jsonWord = json_encode($letters);
shuffle($letters);
?>
<div class="constructor-content-head">
    <h3 data-answers-count="<?= $answersCount; ?>" data-answer-id="<?= $word->id ?>"><?= $word->translates[0]->word; ?></h3>
</div>
<div class="constructor-letters-answer">
    <?php foreach($letters as $letter): ?>
        <div class="constructor-letter">
            <input data-letter-input="" maxlength="0" value="" placeholder="" class="puzzleInput ">
        </div>
    <?php endforeach; ?>
</div>
<div class="constructor-letters-container">
    <?php foreach($letters as $letter): ?>
    <div class="constructor-letter"><?= strtolower($letter); ?></div>
    <?php endforeach; ?>
</div>

<script>
    var word = eval(<?= $jsonWord ?>);
    var wordLength = word.length;
    $('.constructor-letters-container .constructor-letter').bind('click', checkWord);
    $(document).bind('keyup', checkWordKeyUp);
    $(document).bind('keydown', checkWordKeyDown);
    $('.constructor-letter:eq(0)').addClass('next');
    
    function checkWord(letter = null) {
        var container = $(this),
            next = $('.next').index(),
            elem = $('.constructor-letter:eq(' + next + ')');
    
        if(letter.type != "click") {
            $('.constructor-letters-container .constructor-letter').each(function(indexOf, el) {
                var keyLetter = $('.constructor-letters-container .constructor-letter:eq(' + indexOf + ')');
                if(keyLetter.html() == letter && !keyLetter.hasClass('vhidden'))
                    container = keyLetter;
            });
        } 
        
        if(letter == null || letter.type == "click") {
            letter = $.trim(container.html());
            if(letter == '')
                letter = ' ';
        }
        
        if(letter == word[next].toLowerCase()) {
            $('.constructor').find('.next').next('.constructor-letter').addClass('next');
            container.addClass('vhidden');
            elem.addClass('constructor-correct-letter');
            elem.html(letter);
            elem.removeClass('next');
            if(next == wordLength - 1) {
                var LC = parseLanguageAndCategory();
                console.log();
                $.ajax({
                    url: '/site/generate-new-word',
                    type: 'POST',
                    data: {
                        answersCount: $('.constructor-content-head h3').data('answers-count') + 1,
                        answerId: $('.constructor-content-head h3').data('answer-id'),
                        rightAnswer: typeof $('.constructor').find('.constructor-content-head h3').data('wrong-answer') == 'undefined' ? 1 : 0,
                        category: LC[1]
                    },
                    dataType: 'json',
                    success: function(data) {
                        var totalProgress = $('span.constructor-total-progress-number').html();
                        $('span.constructor-current-progress-number').html(data.progress);
                        $('.constructor-current-progress-bar').css('width', data.progress*100/totalProgress + "%");
                        $(".constructor-current-progress-bar").css("transition", "0.4s cubic-bezier(0.75, 0.11, 1, 1)");
                        if(data.end) {
                            setTimeout(function() {
                                //setTimeout(function() { window.location.href = '/site/tasks'; }, 500);
                                $('.main').find('.constructor').slideUp(350);
                                setTimeout(function() { 
                                    $('.main').html(data.result); 
                                    $('.cursorTooltip').html(data.nextLevelIn);
                                    tooltipHover();
                                    setTimeout(makeResult, 300);
                                    $('.main').find('.result').slideDown(350);
                                    $(document).find('.header-progress').html(data.headerProgress);
                                    setTimeout(setLevelProgress, 200);
                                    toggleExperience(false);
                                    setTimeout(function() { toggleLevel(false) }, 900);}, 
                                350);
                                return;
                            },
                            500);
                        } else {
                            $('.constructor-content').html(data.html);
                        }
                    }
                });
                $('.constructor-letters-container .constructor-letter').unbind('click', checkWord);
                $(document).unbind('keyup', checkWordKeyUp);
            }
        } else {
            container.addClass('constructor-wrong-letter');
            $('.constructor').find('.constructor-content-head h3').attr('data-wrong-answer', '');
            setTimeout(function() { container.removeClass('constructor-wrong-letter'); }, 200);
        }
    }
    
    function checkWordKeyUp() {
        checkWord(event.key);
    }
    
    function checkWordKeyDown() {
        if(event.keyCode == 8 || event.keyCode == 32)
            event.preventDefault();
    }
</script>

views/site/block/header_progress.php
<div class="profile-level">
    <?= \Yii::t('main', 'Level'); ?> <?= !empty($userModel) ? $userModel->level : '0'?>
</div>
<div class="profile-experience">
    <div class="profile-experience-progress" 
         data-experience-progress="<?= !empty($userModel) ? $userModel->experience : 0; ?>" 
         data-experience-total="<?= !empty($userModel) ? $userModel->levels->experience : 0; ?>">
    </div>
    <div class="profile-experience-show">
        <?php
        $pointsText = \Yii::t('main', 'очков');
        if(!empty($userModel)) {
            $points = substr($userModel->experience, strlen($userModel->experience)-1);
            if($points == 0) {
                $pointsText = \Yii::t('main', 'очков');
            } elseif($points == 1) {
                $pointsText = \Yii::t('main', 'очко');
            } elseif($points == 2 || $points == 3 || $points == 4) {
                $pointsText = \Yii::t('main', 'очкa');
            } elseif($points == 5 || $points == 6 || $points == 7 || $points == 8 || $points == 9) {
                $pointsText = \Yii::t('main', 'очков');
            }
        }
        ?>
        <?= !empty($userModel) ? $userModel->experience : '0'?> <?= $pointsText; ?>
    </div>
</div>

views/site/block/result.php
<?php
use yii\helpers\Url;
use app\models\ItLanguage;
?>
<div class="result">
    <div class="result-inner">
        <div class="result-words">
            <div class="result-words-container">
                <div class="result-words-mistakes">
                    <div class="result-words-mistakes-title">
                        <h4><?= \Yii::t('main', 'I don\'t know'); ?></h4>
                    </div>
                    <div class="result-words-mistakes-container">
                        <?php foreach($words as $wordId): ?>
                            <?php if(!in_array($wordId, $rightAnswers)): ?>
                            <div class="result-mistake">
                                <?= ItLanguage::findOne(['id' => $wordId])->word ?> - <?= ItLanguage::findOne(['id' => $wordId])->translates[0]->word ?>
                            </div>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                </div>
                <div class="result-words-correct">
                    <div class="result-words-correct-title">
                        <h4><?php echo Yii::t('main', 'I know'); ?></h4>
                    </div>
                    <div class="result-words-correct-container">
                        <?php foreach($rightAnswers as $rightAnswerId): ?>
                        <div class="result-correct">
                            <?= ItLanguage::findOne(['id' => $rightAnswerId])->word ?> - <?= ItLanguage::findOne(['id' => $rightAnswerId])->translates[0]->word ?>
                        </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="result-progress">
            <div class="result-progress-container">
                <div class="result-progress-header">
                    <h2><?= \Yii::t('main', 'Поздравляю!') ?></h2>
                </div>
                <div class="stats-progress">
                    <svg style=" transform: rotate(-90deg); height: 210px; width: 210px;">
                    <circle cx="104" cy="104" r="94" stroke="whitesmoke" stroke-width="20" fill="none"></circle>
                    <circle class="svg-stats-progress" cx="104" cy="104" r="94" stroke="#54b574" 
                            stroke-width="20" fill="none" stroke-dashoffset="0" 
                            stroke-dasharray="0, 999"></circle>
                    </svg>
                    <span class="number-stats">
                        <span id="target-progress-experience" class="number-stats-progress" style="">0</span>
                        /<?= \Yii::$app->user->identity->levels->experience ?>
                    </span>
                </div>
            </div>
            <div class="result-progress-footer">
                <div>
                    <button><a href="<?= Url::toRoute('site/tasks') ?>">Вернуться к тренировкам</a></button>
                </div>
                <div>
                    <button class="continue"><a href="javascript: void(0)" onClick="location.reload();">Продолжить тренировку</a></button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="flash-message">
<?php if((int)substr($gainedExperienceText, 1,1)): ?>
    <div class="flash-gained-experience">
        <div class="flash-gain-exp-img">
        </div>
        <div class="flash-experience-show">
            <?= $gainedExperienceText; ?>
        </div>
    </div>
    <?php if($gainedLevel): ?>
    <div class="flash-gained-level">
        <div class="flash-gain-level-img">
        </div>
        <div class="flash-level-show">
            <?=$gainedLevelText; ?>
        </div>
    </div>
    <?php endif; ?>
<?php endif; ?>
</div>

views/site/block/training.php
<?php
$answerId = rand(0, 4);
$wordsInCase = [];
?>
<div class="training-inner-bg">
    <div class="training-content">
        <div class="no-mobile">
            <div class="col-lg-5 col-xs-12 col-md-12 col-sm-12">
                <h3 class="training-word" data-answers-count="<?= $answersCount; ?>" data-answer-item="<?= $words[0]['main_id'];?>"><?= \Yii::t('main', $words[0]['main_word']) ?></h3>
            </div>
            <div class="col-lg-7 col-xs-7 col-md-7 col-sm-7">
                <div class="col-lg-9 col-xs-9 col-md-9 col-sm-9">
                    <div class="training-translate-list">
                        <ul>
                            <?php for($i = 0; $i < 5; $i++): ?>
                                <?php if($i == $answerId): ?>
                                    <li data-answer-item="<?= $words[0]['translate_id']; ?>">
                                        <a href="javascript: void 0" class="btn">
                                            <b><?= $words[0]['translate_word']; ?></b>
                                        </a> 
                                        <!--<span class="item-number">1</span>-->
                                    </li>
                                <?php elseif($i == 0): ?>
                                    <li data-answer-item="<?= $words[$answerId]['translate_id']; ?>">
                                        <a href="javascript: void 0" class="btn">
                                            <b><?= $words[$answerId]['translate_word']; ?></b>
                                        </a> 
                                        <!--<span class="item-number">1</span>-->
                                    </li>
                                <?php else: ?>
                                    <li data-answer-item="<?= $words[$i]['translate_id']; ?>">
                                        <a href="javascript: void 0" class="btn">
                                            <b><?= $words[$i]['translate_word']; ?></b>
                                        </a> 
                                        <!--<span class="item-number">1</span>-->
                                    </li>
                                <?php endif; ?>
                            <?php endfor; ?>
                            <li class="last">
                                <a href="javascript: void 0" class="btn next btn-blue" data-skip-item id="skip-item">
                                    <b>Не знаю :(</b>
                                </a> 
                                <!--<span class="item-number">1</span>-->
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-xs-3 col-md-3 col-sm-3">
                    <div class="training-timer">
                        <div class="training-round"></div>
                        <div class="training-timer-text">
                            5
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>